<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        if (Service::query()->exists()) {
            return;
        }

        foreach ($this->pages() as $page) {
            Service::query()->create($page);
        }
    }

    private function pages(): array
    {
        return [
            [
                'title' => 'Urgences dentaires',
                'slug' => 'urgence-dentaire',
                'category' => Service::CATEGORY_SOINS,
                'hero_image' => 'assets/images/urgences.jpg',
                'featured_image' => 'assets/images/techonology-img-1.jpg',
                'meta_title' => 'Urgence dentaire',
                'meta_description' => 'Breteuil dentaire — Urgence dentaire',
                'excerpt' => 'Parce que les douleurs bucco-dentaires sont parmi les plus insupportables, nous nous organisons quotidiennement pour prendre en charge les urgences douloureuses et fonctionnelles.',
                'body' => '<h3>Nous choisir en cas d’urgence dentaire</h3><p>Contactez le cabinet au 03 74 47 24 24. Nous organisons la prise en charge des urgences douloureuses et fonctionnelles, du lundi au vendredi, de 9h à 19h.</p>',
                'sort_order' => 1,
                'is_published' => true,
            ],
            [
                'title' => 'Prothèses dentaires',
                'slug' => 'protheses-dentaires',
                'category' => Service::CATEGORY_SOINS,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/techonology-img-3.jpg',
                'meta_title' => 'Prothèse dentaire',
                'meta_description' => 'Breteuil dentaire — Prothèses dentaires',
                'excerpt' => 'L’empreinte est la phase préalable à la réalisation de la prothèse, fabriquée sur-mesure par le prothésiste selon les prescriptions de votre chirurgien-dentiste.',
                'body' => '<h3>Empreinte dentaire</h3><p>La prise d’empreinte est numérique ou réalisée à l’aide d’une pâte. Avant la pose de la prothèse définitive, vous bénéficiez d’une prothèse transitoire amovible ou fixe afin de protéger la dent et de garder le sourire.</p><h3>Les prothèses fixées aux dents</h3><ul><li>La couronne remplace l’ensemble de la partie visible de la dent et la consolide.</li><li>L’inlay remplace une petite partie interne de la dent ; l’onlay est une couronne partielle posée sur la partie externe.</li></ul>',
                'sort_order' => 2,
                'is_published' => true,
            ],
            [
                'title' => 'Dentisterie numérique',
                'slug' => 'dentisterie-numerique',
                'category' => Service::CATEGORY_SOINS,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/dentisterie-numerique.png',
                'meta_title' => 'Dentisterie numérique',
                'meta_description' => 'Breteuil dentaire — Dentisterie numérique',
                'excerpt' => null,
                'body' => '<p>Les nouvelles technologies et l’intelligence artificielle ont bouleversé la médecine dentaire. Dans notre cabinet, vous bénéficiez de soins de dernière génération grâce à nos systèmes d’empreintes numériques, de conception et d’impression 3D.</p><p>Il devient alors possible de réaliser des couronnes ou inlays en une seule séance, avec une grande fiabilité et une grande précision.</p>',
                'sort_order' => 3,
                'is_published' => true,
            ],
            [
                'title' => 'Orthodontie',
                'slug' => 'orthodontie',
                'category' => Service::CATEGORY_SOINS,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/service-single-img.jpg',
                'meta_title' => 'Orthodontie',
                'meta_description' => 'Breteuil dentaire — Orthodontie',
                'excerpt' => 'Aligner les dents pour un sourire plus harmonieux et une meilleure fonction.',
                'body' => '<p>Le cabinet propose un accompagnement orthodontique adapté aux enfants et aux adultes. Après un bilan, nous vous indiquons les solutions les plus adaptées à votre situation.</p>',
                'sort_order' => 4,
                'is_published' => true,
            ],
            [
                'title' => 'Odontologie pédiatrique',
                'slug' => 'odontologie-pediatrique',
                'category' => Service::CATEGORY_SOINS,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/service-single-img.jpg',
                'meta_title' => 'Odontologie pédiatrique',
                'meta_description' => 'Breteuil dentaire — Soins dentaires enfants',
                'excerpt' => 'Des soins adaptés aux enfants, dans un cadre rassurant.',
                'body' => '<p>Nous accueillons les enfants pour le suivi, la prévention et les soins courants, avec une approche pédagogique pour instaurer de bons réflexes dès le plus jeune âge.</p>',
                'sort_order' => 5,
                'is_published' => true,
            ],
            [
                'title' => 'Implant dentaire',
                'slug' => 'implant-dentaire',
                'category' => Service::CATEGORY_IMPLANTOLOGIE,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/Implant-dentaire-Ormoy.png',
                'meta_title' => 'Implant dentaire',
                'meta_description' => 'Breteuil dentaire — Implant dentaire',
                'excerpt' => 'L’implantologie permet de remplacer des dents : un geste esthétique, mais aussi un vrai confort pour les patients qui souffrent de la perte d’une ou plusieurs dents.',
                'body' => '<h3>C’est quoi un implant dentaire ?</h3><p>Un implant dentaire est une petite vis en titane, biocompatible : une racine artificielle qui remplace la racine d’une dent abîmée ou manquante. Il sert de point d’ancrage à une couronne ou une prothèse.</p><p>Votre nouvelle dent aura l’apparence et l’efficacité d’une dent naturelle.</p><h3>Pourquoi des implants dentaires ?</h3><ul><li>Meilleurs résultats esthétiques et fonctionnels.</li><li>Ils limitent la fonte osseuse et l’affaissement du visage.</li><li>Ils évitent de délabrer les dents voisines, contrairement aux techniques traditionnelles.</li><li>Ils offrent une base stable pour parler et manger confortablement.</li></ul>',
                'sort_order' => 10,
                'is_published' => true,
            ],
            [
                'title' => 'Remplacer une dent',
                'slug' => 'remplacer-dent',
                'category' => Service::CATEGORY_IMPLANTOLOGIE,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/Examen-pre-implantaire.jpg',
                'meta_title' => 'Remplacer une dent',
                'meta_description' => 'Breteuil dentaire — Remplacer une dent',
                'excerpt' => 'Un bilan clinique, éventuellement une radiographie ou un scanner 3D, puis un plan de traitement prothétique et chirurgical.',
                'body' => '<h3>Examen pré-implantaire</h3><p>Nos docteurs établissent avec vous un bilan général et bucco-dentaire. Si besoin, une radiographie ou un scanner dentaire 3D sont prévus. Un plan de traitement vous est ensuite remis.</p><h3>Mise en place de l’implant</h3><p>L’implant est positionné dans l’os. Après cicatrisation, la couronne définitive est réalisée pour retrouver esthétique et confort.</p>',
                'sort_order' => 11,
                'is_published' => true,
            ],
            [
                'title' => 'Remplacer plusieurs dents',
                'slug' => 'remplacer-plusieurs-dents',
                'category' => Service::CATEGORY_IMPLANTOLOGIE,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/Mise-en-place-de-l-implant-dentaire.jpg',
                'meta_title' => 'Remplacer plusieurs dents',
                'meta_description' => 'Breteuil dentaire — Remplacer plusieurs dents',
                'excerpt' => 'Plusieurs dents manquantes peuvent être remplacées par des implants, sans agresser les dents restantes.',
                'body' => '<p>Lorsque plusieurs dents manquent, les implants permettent de porter un bridge ou plusieurs couronnes, de façon stable et durable. Le plan de traitement est personnalisé après bilan clinique et imagerie.</p>',
                'sort_order' => 12,
                'is_published' => true,
            ],
            [
                'title' => 'Remplacer toutes les dents',
                'slug' => 'remplacer-toutes-ces-dents',
                'category' => Service::CATEGORY_IMPLANTOLOGIE,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/service-single-img.jpg',
                'meta_title' => 'Remplacer toutes les dents',
                'meta_description' => 'Breteuil dentaire — Remplacer toutes les dents',
                'excerpt' => 'Des solutions implantaires existent pour réhabiliter une arcade complète.',
                'body' => '<p>En cas d’édentation importante, plusieurs implants peuvent porter une prothèse fixe ou une prothèse stabilisée. Le protocole est défini après analyse osseuse et plan de traitement détaillé.</p>',
                'sort_order' => 13,
                'is_published' => true,
            ],
            [
                'title' => 'Chirurgie pré-implantaire',
                'slug' => 'chirurgie-pre-implantaire',
                'category' => Service::CATEGORY_IMPLANTOLOGIE,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/service-single-img.jpg',
                'meta_title' => 'Chirurgie pré-implantaire',
                'meta_description' => 'Breteuil dentaire — Chirurgie pré-implantaire',
                'excerpt' => null,
                'body' => '<h3>L’analyse pré-implantaire</h3><p>La pose d’implants nécessite une préparation (radio, scanner, etc.). Chez certains patients, le volume osseux est insuffisant.</p><p>Pour un ancrage durable, l’implant doit être placé dans un volume osseux suffisant. Une greffe ou un comblement osseux peut alors être proposé (autogreffe ou biomatériau).</p><p>Un bilan osseux préalable définit la technique, le volume à reconstruire et la pose simultanée ou non des implants.</p>',
                'sort_order' => 14,
                'is_published' => true,
            ],
            [
                'title' => 'Conseils post-opératoires',
                'slug' => 'conseils-post-operatiores',
                'category' => Service::CATEGORY_IMPLANTOLOGIE,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/Implant-dentaire-Ormoy.png',
                'meta_title' => 'Conseils post-opératoires',
                'meta_description' => 'Breteuil dentaire — Conseils post-opératoires',
                'excerpt' => 'Après la pose d’implants, les suites sont en général simples si la prémédication a été correctement suivie.',
                'body' => '<h3>Ce qu’il faut faire</h3><ul><li>Prendre tous les médicaments prescrits, même sans douleur.</li><li>Respecter les horaires des antalgiques.</li><li>Appliquer du froid sur la joue les premières heures si indiqué.</li><li>Privilégier une alimentation tiède et molle au début.</li></ul><h3>Ce qu’il faut éviter</h3><ul><li>Le tabac, qui retarde la cicatrisation.</li><li>Les efforts importants les premiers jours.</li><li>De toucher la zone opérée avec la langue ou les doigts.</li></ul>',
                'sort_order' => 15,
                'is_published' => true,
            ],
            [
                'title' => 'Éclaircissement dentaire',
                'slug' => 'eclaircissement-dentaire',
                'category' => Service::CATEGORY_ESTHETIQUE,
                'hero_image' => 'assets/images/tooth-2414909_1920-1024x350-dark.jpg',
                'featured_image' => 'assets/images/tooth-2414909_1920-1024x350.jpg',
                'meta_title' => 'Éclaircissement dentaire',
                'meta_description' => 'Breteuil dentaire — Éclaircissement dentaire',
                'excerpt' => null,
                'body' => '<h3>C’est quoi un blanchiment dentaire ?</h3><p>Le blanchiment éclaircit l’émail à l’aide d’une solution (peroxyde de carbamide ou d’hydrogène) qui agit sur les pigments accumulés avec les années.</p><p>Au fauteuil, on peut gagner jusqu’à 2 teintes en une heure. Le geste peut être répété selon la teinte de départ. Le traitement est indolore ; les résultats sont immédiats.</p>',
                'sort_order' => 20,
                'is_published' => true,
            ],
            [
                'title' => 'Esthétique du sourire',
                'slug' => 'esthetique-sourire',
                'category' => Service::CATEGORY_ESTHETIQUE,
                'hero_image' => 'assets/images/teeth-5120231_640-dark.jpg',
                'featured_image' => 'assets/images/teeth-5120231_640.jpg',
                'meta_title' => 'Esthétique du sourire',
                'meta_description' => 'Breteuil dentaire — Esthétique du sourire',
                'excerpt' => 'La couleur, la forme et l’alignement des dents peuvent évoluer. Dans la grande majorité des cas, des solutions existent sans chirurgie lourde.',
                'body' => '<h3>Couronnes et bridges en zircone ou alumine</h3><p>Votre sourire est notre préoccupation. Nous proposons un ensemble de soins pour retrouver un sourire harmonieux et une bouche en bonne santé : couronnes, bridges, facettes, selon le bilan clinique.</p>',
                'sort_order' => 21,
                'is_published' => true,
            ],
            [
                'title' => 'Facette dentaire',
                'slug' => 'facette-dentaire',
                'category' => Service::CATEGORY_ESTHETIQUE,
                'hero_image' => 'assets/images/Facette-dentaire-Ormoy-dark.jpg',
                'featured_image' => 'assets/images/Facette-dentaire-Ormoy.jpg',
                'meta_title' => 'Facette dentaire',
                'meta_description' => 'Breteuil dentaire — Facette dentaire',
                'excerpt' => null,
                'body' => '<p>Avant un traitement esthétique, nous définissons avec vous vos gênes et vos attentes. Un montage prévisionnel à partir d’un moulage peut visualiser le résultat.</p><p>Une facette est une fine coque en céramique collée sur la face externe des dents. Elle corrige la forme, la position, la teinte et l’aspect de surface.</p><p>Après empreinte et dents provisoires, les facettes sont posées en général dans un délai d’une semaine.</p>',
                'sort_order' => 22,
                'is_published' => true,
            ],
            [
                'title' => 'Facette pelliculaire',
                'slug' => 'facette-pelliculaire',
                'category' => Service::CATEGORY_ESTHETIQUE,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/Facette-dentaire-pelliculaire.png',
                'meta_title' => 'Facette pelliculaire',
                'meta_description' => 'Breteuil dentaire — Facette pelliculaire',
                'excerpt' => null,
                'body' => '<p>Les facettes pelliculaires sont une référence des céramiques dentaires : qualité cosmétique et résistance éprouvées.</p><p>Aussi fines qu’une lentille de contact, elles couvrent la zone du sourire. Le praticien réalise éventuellement une taille minimale, puis une empreinte et des dents provisoires avant le collage.</p>',
                'sort_order' => 23,
                'is_published' => true,
            ],
            [
                'title' => 'Aligneurs invisibles',
                'slug' => 'aligneurs-invisibles',
                'category' => Service::CATEGORY_ESTHETIQUE,
                'hero_image' => 'assets/images/protese.jpg',
                'featured_image' => 'assets/images/service-single-img.jpg',
                'meta_title' => 'Aligneurs invisibles',
                'meta_description' => 'Breteuil dentaire — Aligneurs invisibles',
                'excerpt' => 'Un alignement discret, gouttière après gouttière.',
                'body' => '<p>Les aligneurs transparents permettent de corriger de nombreux décalages dentaires de façon progressive et esthétique. Un bilan détermine si cette solution vous convient.</p>',
                'sort_order' => 24,
                'is_published' => true,
            ],
        ];
    }
}
